### PR TITLE
Refactor print progress of ImageNet training

### PR DESCRIPTION
**Pull request by pmeier**
This refactors the printing of the progress during the ImageNet training / evaluation. To achieve this every `AverageMeter` now has a `name`, a value format (`fmt`), and a  `__str__()` method for easy printing.

Furthermore, the new `ProgressMeter` bundles the `AverageMeter`s to ease up the interface even more.

### CODE REVIEW

**Comment by soumith** [comment]
looks great. thanks!

**Comment by shippingwang** [comment]
It raised an error:
image

**Comment by pmeier** [comment]
It works fine for me. [Line 301](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L301) is empty. Did you insert something?

**Comment by zzchust** [comment]
> @pmeier It raised an error:
> image

I have the same problem for python2.7, torch0.4
while use python3,torch1.0 is ok

Anyone know the reason ?

**Comment by pmeier** [comment]
@zzchust I can only repeat myself:

> [Line 301](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L301) is empty. Did you insert something?

If the answer is _no_,  can you try to insert
```python
from __future__ import print_function
```
in the file header? I'm unable to test it myself with python2 right now.

**Comment by zzchust** [comment]
> @zzchust I can only repeat myself:
> 
> > [Line 301](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L301) is empty. Did you insert something?
> 
> If the answer is _no_, can you try to insert
> 
> ```python
> from __future__ import print_function
> ```
> 
> in the file header? I'm unable to test it myself with python2 right now.

I try your suggestion, then raise another error
image

**Comment by pmeier** [comment]
[Line 322 (and 323 with the additional `import`)](https://github.com/pytorch/examples/blob/5b1f45057dc14a5e2132b45233c258a1dc2a0aab/imagenet/main.py#L322-L323) do not contain the method header contained in your screenshot. The method header is defined in [line  376](https://github.com/pytorch/examples/blob/5b1f45057dc14a5e2132b45233c258a1dc2a0aab/imagenet/main.py#L376). I cannot help you, if you work with a modified version.

**Comment by zzchust** [comment]
> [Line 322 (and 323 with the additional `import`)](https://github.com/pytorch/examples/blob/5b1f45057dc14a5e2132b45233c258a1dc2a0aab/imagenet/main.py#L322-L323) do not contain the method header contained in your screenshot. The method header is defined in [line 376](https://github.com/pytorch/examples/blob/5b1f45057dc14a5e2132b45233c258a1dc2a0aab/imagenet/main.py#L376). I cannot help you, if you work with a modified version.

I see. I give up this fancy feature in python2.

**Pull request merged**
