### PR TITLE
add flush to print

### PR DESCRIPTION
**Pull request by fyu**
With flush, log info can appear immediately when it is directed to a pipe or file.

### CODE REVIEW

**Comment by apaszke** [comment]
This will break in Python 2, as `print` is not a function there 😕

**Comment by fmassa** [comment]
@apaszke should we add `from __future__ import print_function`, or your prefer not to rely on that?

**Comment by fyu** [comment]
print as a function is already used in master. This PR only adds an argument to the function. To make it compatible, we can have an additional PR to import print_function from __future__.

**Comment by apaszke** [comment]
It's not used as a function. `print('asdf')` works both in Python 2 and 3. In 2 it just evaluates as a statement + an expression in parenthesis. We can merge it if you import the function.

**Comment by fyu** [comment]
I see. thanks for the explanation. will do.

**Comment by Maratyszcza** [comment]
This fails on Python 2.7: `Traceback (most recent call last):
  File "main.py", line 290, in <module>
    main()
  File "main.py", line 66, in main
    print("=> creating model '{}'".format(args.arch), flush=True)
TypeError: 'flush' is an invalid keyword argument for this function`

**Comment by colesbury** [comment]
I'm going to revert this change. You can get the buffering behavior with either of the following:

```
unbuffer python main.py
python -u main.py
```

https://linux.die.net/man/1/unbuffer
https://docs.python.org/2/using/cmdline.html#cmdoption-u

**Pull request merged**
