### PR TITLE
Add mps device

### PR DESCRIPTION
**Pull request by YuliyaPylypiv**
Added mps device to some networks

### CODE REVIEW

**Comment by msaroufim** [comment]
Hmm I'd be curious how many of the existing examples break with this change. I don't have an M1 and can't easily integrate into Github actions - do you mind running `run_python_examples.sh` locally and pasting the logs here

**Review by hudeven — CHANGES_REQUESTED** [review]
Hi @YuliyaPylypiv, thanks for your contribution! To move forward, could you resolve @msaroufim 's comment?

**Comment by YuliyaPylypiv** [comment]
Hi @msaroufim, please see the log from `run_python_examples.sh` attached with the latest changes from my branch. Ran those on M1 MacBook Air 8 GB + macOS Ventura 13.0 Beta (22A5295i)
[examples_out.txt](https://github.com/pytorch/examples/files/9428724/examples_out.txt)

**Comment by kulinseth** [comment]
@msaroufim , are there any plans to add the M1 workflows for PyTorch examples ? We have some machines used in ```ciflow/mps``` for pytorch/pytorch project.

**Review by hudeven — APPROVED** [review]
LGTM. @YuliyaPylypiv thanks for your contribution!

**Comment by kulinseth** [comment]
@facebook-github-bot -h

**Comment by kulinseth** [comment]
@hudeven , is there a bot merge command to check this in ?

**Pull request merged**
