### PR TITLE
specify train and eval mode for netG and netD

### PR DESCRIPTION
**Pull request by iammarvelous**

### CODE REVIEW

**Comment by soumith** [comment]
this is not really necessary. are you doing this in an attempt to save computation, or to get BatchNorm statistics right?

**Comment by iammarvelous** [comment]
@soumith Yes. Maybe it won't influence the final result much. But it could corrupt BatchNorm statistics technically. And as a tutorial sample for new users to learn, it is good to remind them of using `train` and `eval` mode.

**Comment by soumith** [comment]
your change in line 257 seems fine.
But your changes in other places seem inappropriate because the learning is very stochastic, and it is better to rely on batch statistics than running_mean / running_std in those places..

**Comment by iammarvelous** [comment]
Well, it may not be the case. Since what we want are better generative results on `eval` mode rather than based on batch statistics, we should also treat the same for the input of D, right? Technically, I didn't see a problem there. But did you mean it may lead to some converge problems?

**Comment by soumith** [comment]
i'm just saying that batch statistics are of better quality, so we should rather use those.
I'm not sure it leads to convergence problems though.

**Pull request closed without merging**
