### PR TITLE
Add linear layer to time series prediction

### PR DESCRIPTION
**Pull request by t-vi**
As is the final network output is modulated with a tanh nonlinearity.
This is undesirable. As a simple / realistic fix we add a final
linear layer.

This addresses #243.

### CODE REVIEW

**Comment by soumith** [comment]
thanks a lot for investigating and fixing it Thomas!

**Comment by barnabytprowe** [comment]
Nice!

**Comment by barnabytprowe** [comment]
A quick question @t-vi , as someone interested to learn - was the tanh nonlinearity in the output a bad idea in this specific example, or is it one _in general_?

**Comment by t-vi** [comment]
@barnabytprowe, it really depends on the nature of what you are learning. Here, the tanh would have required the input to the tanh to get extremely large/small to reproduce values at +/- 1 or very close. This - that you need extremely large values - is a bad idea in general.
On the other hand, if you know that values close to +/-1 are extremely improbable, you might go with tanh at the end.
(we might move to the [discussion forums](https://discuss.pytorch.org/), I'm tom there)

**Comment by barnabytprowe** [comment]
A belated thank you for the explanation @t-vi / Tom - makes total sense

**Pull request merged**
