### PR TITLE
Add a time sequence prediction example

### PR DESCRIPTION
**Pull request by maplewizard**
Hi,
I have made a time sequence prediction example, which I think, is capable to illustrate the usage of LSTMCell in pytorch. It's enough simple and fun and is a good small case for beginners who are interested in either pytorch or time sequence. 
Please feel free to tell me if it go against of your principles of designing the examples. I'll try to make it more friendly and easy to use for beginners.

### CODE REVIEW

**Comment by soumith** [comment]
OpenNMT has been moved to https://github.com/OpenNMT/OpenNMT-py and will be continuing development there by the OpenNMT team and other community members.

Please send pull requests over there.

Thank you.

**Comment by maplewizard** [comment]
Dear @soumith, I'm sorry for modified a small bug in OpenNMT while submit it with a new example. This is a new example to show how to do time sequence prediction with pytorch and it have no relation with OpenNMT. Can I submit this new example again without the modification of OpenNMT?

**Comment by soumith** [comment]
actually, sorry i didn't notice. Yes, your example will be helpful. can you open a PR without the OpenNMT modification?
Thanks.

**Comment by maplewizard** [comment]
@soumith I have created another pull request: https://github.com/pytorch/examples/pull/118 . Please check it. Thanks.

**Pull request closed without merging**
