### PR TITLE
docs: added copyright holder to license file

### LINKED ISSUE #902: License file doesn't include any owner
The copyright line in the license file should include both the year **AND** owner but there is currently no owner.  See https://opensource.org/licenses/BSD-3-Clause.

### PR DESCRIPTION
**Pull request by david-pa**
Fixes #902

### CODE REVIEW

**Review by spzala — COMMENTED** [review]
@david-pa thanks for the quick PR. Suggest to change your changes to `Copyright (c) 2017, Pytorch contributors`. Also, please mention the issue link in the PR description along with a brief description of the issue. 
cc @msaroufim for review request.

**Comment by david-pa** [comment]
@msaroufim Ready for review!

**Comment by david-pa** [comment]
@pritamdamania87 @H-Huang please review.

**Review by spzala — APPROVED** [review]
@david-pa thanks for addressing my comment. Changes looks good to me and in line with other repos.

**Comment by spzala** [comment]
Hi @msaroufim yup :) but please see here https://github.com/pytorch/tutorials/blob/main/LICENSE

**Review by msaroufim — APPROVED** [review]

**Comment by spzala** [comment]
Thanks @msaroufim !!

**Pull request merged**
