### PR TITLE
updated CartPole-v0 to CartPole-v1

### PR DESCRIPTION
**Pull request by nitesh4146**
Minor update: `CartPole-v0` is out of date, therefore updated to `CartPole-v1`

### CODE REVIEW

**Comment by msaroufim** [comment]
Cool I'd suggest making sure the example still works by running the test `python reinforce.py` and printing the logs here

**Comment by nitesh4146** [comment]
@msaroufim, The changes were only made to `actor_critic.py` file. The model achieves target average reward in 930 episodes.
 
Log with default seed: [Actor-Critic Log](https://www.dropbox.com/s/xq282asb6suz9ff/ac_log.txt?dl=0)

**Comment by msaroufim** [comment]
Gotcha do you mind then adding a test here for `python actor_critic.py` as well? https://github.com/pytorch/examples/blob/main/run_python_examples.sh

**Comment by nitesh4146** [comment]
Added test for actor_critic to the script and updated corresponding error messages. The script runs locally without any problem. here's the [log](https://www.dropbox.com/s/nk5rgfyad1xee04/log.txt?dl=0) for both `reinforce` and `actor_critic` after running the script locally.

**Pull request merged**
