### PR TITLE
[WIP] Adding controlnet

### PR DESCRIPTION
**Pull request by arunppsg**
#1131

This pull request adds a new example of controlnet model in pytorch.

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @arunppsg are you still interested in merging this? I think you're close

**Comment by arunppsg** [comment]
The original controlnet model is big and I am not able to test it in my machine. I also need to add a couple of more components to the model. I have a question: Should we make a small minimal implementation, like [min-GPT](https://github.com/pytorch/examples/tree/6fc19c76b9f5550d8d3cb38284845ac7ed14223c/distributed/minGPT-ddp) or do an implementation of full model? I think the former approach will be good for an example and latter one is already available at [ControlNet](https://github.com/lllyasviel/ControlNet).

**Comment by msaroufim** [comment]
Minimal is usually better for this repo

**Comment by arunppsg** [comment]
Sounds good, I will work on making a minimal prototype by end of Aug.

**Pull request closed without merging**
