### PR TITLE
tweak running examples without cuda

### PR DESCRIPTION
**Pull request by mattip**
Tweak the `run_python_examples.sh` script to complete in ~5 minutes (on my machine) without CUDA. Once this is merged, we can consider adding #704 to actually run the examples as part of CI.

TBD: how do we get a pre-release version of torch/torchvision in order to test the latest HEAD? Perhaps it should be a pytorch/pytorch cron job that runs once a day or once a week?

ping @jlin27

### CODE REVIEW

**Comment by brianjo** [comment]
You can install and run the nightly build using:
```pip install numpy
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
```

Per pytorch.org install matrix. You might have to install nightlies for audio, vision and others to get this to work.

**Comment by brianjo** [comment]
> You can install and run the nightly build using:
> 
> ```
> pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
> ```
> 
> Per pytorch.org install matrix. You might have to install nightlies for audio, vision and others to get this to work.

Sorry, for non cuda nightly builds on Linux, the pip command is: 

pip install numpy
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html 

Cheers

**Comment by mattip** [comment]
@soumith reworked dry_run handling in d0447a1

**Comment by mattip** [comment]
I checked that this PR did not introduce breakage. There is a problem with `dcgan` and PyTorch 1.7: it is using a deprecated construct. When I do a PR to add CI, that will need to be fixed to make the CI pass.

**Pull request merged**
