### PR TITLE
enhancing readability

### PR DESCRIPTION
**Pull request by andrewnaguib**
Removing `sys` package as it wasn't used. Also, renaming all `input` instances to `predictor` as `input` is a builtin keyword.

### CODE REVIEW

**Comment by soumith** [comment]
we are explicitly not planning to change `input`, as it's the best word that describes it. `predictor` doesn't even come close.

Removing the `sys` package sounds good.

**Comment by andrewnaguib** [comment]
Maybe we can capitalize INPUT?

On Jan 21, 2019, at 01:05, Soumith Chintala <notifications@github.com<mailto:notifications@github.com>> wrote:


we are explicitly not planning to change input, as it's the best word that describes it. predictor doesn't even come close.

Removing the sys package sounds good.

**Comment by soumith** [comment]
capitalizing input just looks weird. none of the other variables will be capitalized.

In the context of just this example, `images` might make sense.

**Comment by soumith** [comment]
thanks!

**Pull request merged**
